file_name='cam.png';
[cover_boject,map]=imread(file_name);
cover_boject=uint8(cover_boject);   %%转换为uints数
one=bitget(cover_boject,1);
two=bitget(cover_boject,2);
three=bitget(cover_boject,3);
four=bitget(cover_boject,4);
five=bitget(cover_boject,5);
six=bitget(cover_boject,6);
seven=bitget(cover_boject,7);
eight=bitget(cover_boject,8);

figure(1)
subplot(2,4,1);
imshow(one,[])
title('低位第1位')
subplot(2,4,2);
imshow(two,[])
title('低位第2位')
subplot(2,4,3);
imshow(three,[])
title('低位第3位')
subplot(2,4,4);
imshow(four,[])
title('低位第4位')
subplot(2,4,5);
imshow(five,[])
title('低位第5位')
subplot(2,4,6);
imshow(six,[])
title('低位第6位')
subplot(2,4,7);
imshow(seven,[])
title('低位第7位')
subplot(2,4,8);
imshow(eight,[])
title('低位第8位')